github: [jaytech123]              # GitHub Sponsors-enabled username
patreon: jaypatreon               # Patreon username
open_collective: jaycollective    # Open Collective username
ko_fi: jayko                      # Ko-fi username
tidelift: npm/jay-package         # Format: platform/package-name
community_bridge: jay-project     # Community Bridge project name
liberapay: jaylibera              # Liberapay username
issuehunt: jayissues              # IssueHunt username
lfx_crowdfunding: jay-crowdfund   # LFX Crowdfunding project
polar: jaypolar                   # Polar username
buy_me_a_coffee: jaycoffee        # Buy Me a Coffee username
thanks_dev: jaythanks             # thanks.dev username
